const EVENT = {
  INITIATE_CAPTURE: "INITIATE_CAPTURE",
  SELECT_CAPTURE_SCREEN: "SELECT_CAPTURE_SCREEN",
  STOP_CAPTURE_SCREEN: "STOP_CAPTURE_SCREEN",
  HAS_INITIATED_CAPTURE_SCREEN: "HAS_INITIATED_CAPTURE_SCREEN",
  HAS_STOPPED_CAPTURE_SCREEN: "HAS_STOPPED_CAPTURE_SCREEN",
};

module.exports = EVENT;
